name: Dockerfile Deploy

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout to the branch
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Log in to container registry
      uses: docker/login-action@v3
      with:
        registry: mvp10k.azurecr.io
        username: ${{secrets.mvp10k_USERNAME_00EC}}
        password: ${{secrets.mvp10k_PASSWORD_00EC}}
        
    - name: Build and push container image to registry
      uses: docker/build-push-action@v5
      with:
        context: src/PasswordPurgatory/PasswordPurgatory.Web
        push: true
        tags: |
          mvp10k.azurecr.io/passwordpurgatoryweb:latest
        secrets: |
          telerik_key=${{secrets.TELERIK_NUGET_KEY}}

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{secrets.passwordpurgatoryweb_app_2024091_SPN}}
        
    - name: Deploy to containerapp
      uses: azure/CLI@v1
      with:
        inlineScript: >
          az config set extension.use_dynamic_install=yes_without_prompt

          az containerapp registry set --name passwordpurgatoryweb-app-2024091 --resource-group password-purgatory --server mvp10k.azurecr.io --username ${{secrets.mvp10k_USERNAME_00EC}} --password ${{secrets.mvp10k_PASSWORD_00EC}}

          az containerapp update --name passwordpurgatoryweb-app-2024091 --container-name passwordpurgatoryweb --resource-group password-purgatory --image mvp10k.azurecr.io/passwordpurgatoryweb:latest
    
    - name: logout
      run: >
        az logout
