name: .NET SDK Deploy

on:
  workflow_dispatch:

env:
  CSPROJ_PATH: src/PasswordPurgatory/PasswordPurgatory.Web/PasswordPurgatory.Web.csproj
  DOTNET_RID: linux-x64
  NUGETCONFIG_PATH: src/PasswordPurgatory/NuGet.Config
  TELERIK_NUGET_KEY: ${{ secrets.TELERIK_NUGET_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout to the branch
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Log in to container registry
      uses: azure/docker-login@v2
      with:
        login-server: mvp10k.azurecr.io
        username: ${{secrets.mvp10k_USERNAME_00EC}}
        password: ${{secrets.mvp10k_PASSWORD_00EC}}

    - name: Restore
      run: dotnet restore "${{env.CSPROJ_PATH}}" -r ${{env.DOTNET_RID}} --configfile ${{env.NUGETCONFIG_PATH}}

    - name: Build and push container image to registry
      run: dotnet publish ${{env.CSPROJ_PATH}} -c Release -r ${{env.DOTNET_RID}} -p:PublishProfile=DefaultContainer -p:ContainerImageTag=latest --no-restore --no-self-contained -p:ContainerRegistry='mvp10k.azurecr.io' -p:ContainerRepository="passwordpurgatoryweb" -bl

    - name: Upload binlog for investigation
      uses: actions/upload-artifact@v4
      with:
        if-no-files-found: error
        name: binlog
        path: msbuild.binlog

    - name: Az Login
      uses: azure/login@v2
      with:
        creds: ${{secrets.passwordpurgatoryweb_app_2024091_SPN}}

    - name: Az Container App Deploy
      uses: azure/CLI@v2
      with:
        scriptType: 'ps'
        scriptLocation: inlineScript
        inlineScript: |
          az config set extension.use_dynamic_install=yes_without_prompt

          az containerapp registry set --name passwordpurgatoryweb-app-2024091 --resource-group password-purgatory --server mvp10k.azurecr.io --username ${{secrets.mvp10k_USERNAME_00EC}} --password ${{secrets.mvp10k_PASSWORD_00EC}}

          az containerapp update --name passwordpurgatoryweb-app-2024091 --container-name passwordpurgatoryweb --resource-group password-purgatory --image mvp10k.azurecr.io/passwordpurgatoryweb:latest

    - name: Az Logout
      run: az logout

