name: Publish Azure Web App
on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - 'src/PasswordPurgatory/PasswordPurgatory.Web/**/*' 
  #     - '.github/workflows/publish-azure-webapp.yml'

env:
  AZURE_WEBAPP_NAME: PasswordPurgatoryWeb
  AZURE_WEBAPP_PACKAGE_PATH: PasswordPurgatory.Web/publish
  AZURE_WEBAPP_PUBLISH_PROFILE: ${{ secrets.PasswordPurgatoryWeb_b8f5 }}
  CSPROJ_PATH: src/PasswordPurgatory/PasswordPurgatory.Web/PasswordPurgatory.Web.csproj
  NUGETCONFIG_PATH: src/PasswordPurgatory/NuGet.Config
  TELERIK_NUGET_KEY: ${{ secrets.TELERIK_NUGET_KEY }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore
      run: dotnet restore "${{ env.CSPROJ_PATH }}" --configfile ${{ env.NUGETCONFIG_PATH }}
      
    - name: Publish
      run: dotnet publish "${{ env.CSPROJ_PATH }}" -o "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}" --no-restore

    - name: Deploy to Azure WebApp
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        publish-profile: ${{ env.AZURE_WEBAPP_PUBLISH_PROFILE }}

    - name: Publish Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: webapp
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
