name: Publish Docker Image (GHCR)

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'src/PasswordPurgatory/PasswordPurgatory.Web/**'

permissions:
  contents: read
  packages: write

env:
  CSPROJ_PATH: src/PasswordPurgatory/PasswordPurgatory.Web/PasswordPurgatory.Web.csproj
  DOTNET_RID: linux-x64

jobs:
  publish-ghcr:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout to the branch
      uses: actions/checkout@v6

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '10.0.x'

    - name: Set GHCR image repository
      run: echo "GHCR_IMAGE_REPOSITORY=${GITHUB_REPOSITORY_OWNER,,}/passwordpurgatoryweb" >> "$GITHUB_ENV"

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v4
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}

    - name: Build and push container image to GitHub Container Registry
      run: dotnet publish ${{env.CSPROJ_PATH}} -c Release -r ${{env.DOTNET_RID}} -p:PublishProfile=DefaultContainer -p:ContainerImageTag=latest -p:ContainerRegistry='ghcr.io' -p:ContainerRepository="$GHCR_IMAGE_REPOSITORY"

    - name: Invoke Portainer webhook
      run: curl --fail --request POST ${{secrets.PORTAINER_WEBHOOK_URL}}

      