name: Publish Azure Function

on:
  push:
      - main
    paths:
      - 'src/PasswordPurgatory/PasswordPurgatory.ApiFunction/**/*' 
      - '.github/workflows/publish-azure-functions.yml'

env:
  AZURE_FUNCTIONAPP_NAME: api-password-purgatory
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'src/PasswordPurgatory/PasswordPurgatory.ApiFunction/'
  DOTNET_VERSION: '6.0.400'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: 'Checkout repo'
      uses: actions/checkout@master

    - name: Setup DotNet ${{ env.DOTNET_VERSION }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: 'Build'
      id: build
      shell: bash
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        dotnet build --configuration Release --output ./output
        popd
        
    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: publish-apifunction
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}